# Generated by Django 2.2 on 2019-04-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='disposition',
            field=models.CharField(max_length=20),
        ),
    ]
