# Generated by Django 2.2 on 2019-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_auto_20190429_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='endofsupport',
            field=models.DateField(blank=True),
        ),
    ]
